(() => {
  const $ = s => document.querySelector(s);
  const state = Portal.load();
  const editor = $('#editor'); const saida = $('#saida');
  function persist(){ state.ultimoAcesso=new Date().toISOString(); Portal.save(state); render(); }
  function grantXP(v){ state.xp += v; }
  function renderAvisos(){ const el=$('#lista-avisos'); if(!el) return; el.innerHTML=AVISOS.map(a=>`<article class="card aviso ${a.tipo}"><h4>${a.titulo}</h4><p>${a.mensagem}</p><small>${a.data}</small></article>`).join(''); }
  function renderTrilhas(){ const el=$('#lista-trilhas'); if(!el) return; el.innerHTML=TRILHAS.map(t=>`<article class='card'><h4>${t.titulo}</h4><p>${t.descricao}</p><small>${t.dificuldade} • ${t.xp} XP</small><button class='btn' data-trilha='${t.id}'>Iniciar</button></article>`).join(''); el.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!state.trilhasConcluidas.includes(b.dataset.trilha)){state.trilhasConcluidas.push(b.dataset.trilha);grantXP(150);persist();}}); }
  function renderModulos(){ const el=$('#lista-modulos'); if(!el) return; el.innerHTML=MODULOS.map(m=>`<article class='card'><h4>${m.titulo}</h4><p>${m.descricao}</p><pre>${m.pseudo}</pre><details><summary>Comparar linguagens</summary><code><strong>C#</strong>\n${m.comparacao?.csharp||'-'}\n\n<strong>Java</strong>\n${m.comparacao?.java||'-'}\n\n<strong>JavaScript</strong>\n${m.comparacao?.javascript||'-'}\n\n<strong>Python</strong>\n${m.comparacao?.python||'-'}</code></details><p><em>Atividade:</em> ${m.atividade||'Pratique com um exemplo próprio.'}</p><button class='btn' data-mod='${m.id}'>Concluir (+50 XP)</button></article>`).join(''); el.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(!state.modulosConcluidos.includes(b.dataset.mod)){state.modulosConcluidos.push(b.dataset.mod);grantXP(50);if(state.modulosConcluidos.length===MODULOS.length)grantXP(500);persist();}}); }
  function renderDesafios(){ const el=$('#lista-desafios'); if(!el) return; el.innerHTML=DESAFIOS.map(d=>`<article class='card'><h4>${d.titulo}</h4><p>${d.comando}</p><small>${d.nivel} • ${d.xp} XP</small><button class='btn' data-load='${d.id}'>Carregar</button></article>`).join(''); el.querySelectorAll('button').forEach(b=>b.onclick=()=>{const d=DESAFIOS.find(x=>x.id===b.dataset.load);editor.value=d.codigoInicial||'';}); }
  function renderGamificacao(){ state.conquistas=CONQUISTAS.filter(c=>c.check(state)).map(c=>c.id); const lc=$('#lista-conquistas'); const lm=$('#lista-missoes'); if(lc) lc.innerHTML=CONQUISTAS.map(c=>`<article class='card ${state.conquistas.includes(c.id)?'ok':''}'>${c.titulo}</article>`).join(''); if(lm) lm.innerHTML=MISSOES.map(m=>`<article class='card ${m.check(state)?'ok':''}'>${m.titulo}</article>`).join(''); $('#proxima-missao').textContent = MISSOES.find(m=>!m.check(state))?.titulo || 'Todas concluídas!'; }
  function renderRanking(){ const el=$('#lista-ranking'); if(!el) return; el.innerHTML=Ranking.get().map(r=>`<li>${r.nome} — ${r.xp} XP</li>`).join(''); }
  function render(){ $('#xp-total').textContent=state.xp; $('#modulos-concluidos').textContent=state.modulosConcluidos.length; renderGamificacao(); renderRanking(); }

  $('#btn-executar').onclick=()=>{ try{ const r=Pseudo.run(editor.value); saida.textContent=r.out.join('\n')||'Execução concluída sem saída.'; state.execucoes++; if(!state.usouLab){state.usouLab=true;grantXP(20);} persist(); } catch(e){ saida.textContent='Erro amigável: '+e.message; } };
  $('#btn-verificar').onclick=()=>{ const txt=editor.value.toUpperCase(); const d=DESAFIOS.find(x=>txt.includes((x.criterios[0]||'').toUpperCase())); if(d){ if(!state.desafiosConcluidos.includes(d.id)){state.desafiosConcluidos.push(d.id); grantXP(d.xp);} saida.textContent='Muito bem! Seu algoritmo executou corretamente. Continue praticando.'; } else saida.textContent='Seu código executou, mas faltam critérios do desafio.'; persist(); };
  $('#btn-limpar').onclick=()=>editor.value=''; $('#btn-copiar').onclick=()=>navigator.clipboard?.writeText(editor.value); $('#btn-salvar').onclick=()=>localStorage.setItem('portalEditor',editor.value); $('#btn-restaurar').onclick=()=>editor.value=localStorage.getItem('portalEditor')||'';
  const sel=$('#exemplo-select'); Object.keys(EXEMPLOS).forEach(k=>{const o=document.createElement('option');o.textContent=k;sel.appendChild(o);}); $('#btn-carregar-exemplo').onclick=()=>editor.value=EXEMPLOS[sel.value];
  $('#btn-ranking-salvar').onclick=()=>{Ranking.update(state.perfil.nome,state.xp);renderRanking();}; $('#btn-ranking-limpar').onclick=()=>{Ranking.clear();renderRanking();};
  $('#btn-exportar').onclick=()=>Professor.exportar(state); $('#btn-copiar-desafios').onclick=()=>Professor.copiarDesafios(); $('#btn-resetar').onclick=()=>{localStorage.removeItem(Portal.KEY);location.reload();};
  const modal=$('#modal-perfil'); $('#btn-editar-perfil').onclick=()=>{ $('#perfil-nome').value=state.perfil.nome; $('#perfil-turma').value=state.perfil.turma; $('#perfil-avatar').value=state.perfil.avatar; modal.showModal(); };
  $('#form-perfil').addEventListener('submit',()=>{ state.perfil={nome:$('#perfil-nome').value,turma:$('#perfil-turma').value,avatar:$('#perfil-avatar').value||'🧑‍💻'}; persist();});
  renderAvisos(); renderTrilhas(); renderModulos(); renderDesafios(); render();
})();
